# Generated by Django 5.0.1 on 2024-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_movie_director_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_email',
            field=models.EmailField(blank=True, default='sugar_daddy@gmail.com', max_length=254),
        ),
    ]
